#!/usr/bin/env bash
set -euo pipefail

readonly REDIS_INSTALL_PREFIX="/usr/local/redis"
readonly REDIS_BACKUP_ROOT="/usr/local/redis-backups"
readonly REDIS_SERVICE_NAME="redis.service"
readonly REDIS_SERVICE_UNIT="/etc/systemd/system/redis.service"
readonly REDIS_USER="redis"
readonly REDIS_GROUP="redis"
readonly REDIS_PACKAGE_ID="redis-unofficial-builds"
readonly REDIS_STATE_FILE="$REDIS_INSTALL_PREFIX/.redis-package-state"
readonly REDIS_UNIT_MARKER="# Managed by redis-unofficial-builds"

detect_ui_language() {
  local requested_locale
  requested_locale="${REDIS_INSTALL_LANG:-${LC_ALL:-${LC_MESSAGES:-${LANG:-en}}}}"
  case "$requested_locale" in
    zh*|ZH*) printf 'zh\n' ;;
    *) printf 'en\n' ;;
  esac
}

readonly REDIS_UI_LANGUAGE="$(detect_ui_language)"

message() {
  local key="$1"
  local format
  shift

  if [[ "$REDIS_UI_LANGUAGE" == "zh" ]]; then
    case "$key" in
      root_required) format='此脚本必须使用 root 权限运行。' ;;
      command_missing) format='缺少必需命令：%s' ;;
      package_server_missing) format='安装包中缺少 redis-server：%s' ;;
      package_cli_missing) format='安装包中缺少 redis-cli：%s' ;;
      package_config_missing) format='安装包中缺少 redis.conf：%s' ;;
      package_unit_missing) format='安装包中缺少 redis.service：%s' ;;
      package_info_missing) format='安装包中缺少 PACKAGE-INFO：%s' ;;
      package_info_invalid) format='PACKAGE-INFO 无效或不是本项目生成的安装包：%s' ;;
      package_prefix_invalid) format='安装包要求的安装目录不是 %s。' ;;
      linux_required) format='此安装包只能在 Linux 上运行；当前系统为 %s。' ;;
      arch_unsupported) format='不支持当前 CPU 架构：%s' ;;
      arch_mismatch) format='安装包架构为 %s，但当前系统架构为 %s。' ;;
      glibc_too_old) format='当前 glibc 为 %s，安装包至少需要 glibc %s。' ;;
      binary_failed) format='新 redis-server 无法在当前系统运行：%s' ;;
      version_unreadable) format='无法读取新 redis-server 的版本。' ;;
      version_mismatch) format='PACKAGE-INFO 声明 Redis %s，但二进制报告 %s。' ;;
      systemd_unavailable) format='systemd 未运行。可在启用了 systemd 的主机上安装，或使用 --no-service 仅安装程序。' ;;
      unit_replace) format='由于指定了 --force-service，将替换现有服务单元：%s' ;;
      unit_conflict) format='%s 已由其他安装管理。确认允许替换时使用 --force-service。' ;;
      group_created) format='已创建系统用户组 %s。' ;;
      user_created) format='已创建系统用户 %s。' ;;
      service_failed) format='%s 未能保持运行状态，请检查：journalctl -u %s' ;;
      state_invalid) format='安装状态文件无效：%s' ;;
      unmanaged_install) format='发现未由本项目管理的 Redis 安装。确认迁移时重新运行并添加 --adopt。' ;;
      unexpected_path) format='拒绝操作非预期路径：%s' ;;
      unknown_option) format='未知选项：%s' ;;
      *) format="$key" ;;
    esac
  else
    case "$key" in
      root_required) format='This script must be run as root.' ;;
      command_missing) format='Required command not found: %s' ;;
      package_server_missing) format='redis-server is missing from the package: %s' ;;
      package_cli_missing) format='redis-cli is missing from the package: %s' ;;
      package_config_missing) format='redis.conf is missing from the package: %s' ;;
      package_unit_missing) format='redis.service is missing from the package: %s' ;;
      package_info_missing) format='PACKAGE-INFO is missing from the package: %s' ;;
      package_info_invalid) format='PACKAGE-INFO is invalid or was not generated by this project: %s' ;;
      package_prefix_invalid) format='The package install prefix is not %s.' ;;
      linux_required) format='This package only runs on Linux; the current system is %s.' ;;
      arch_unsupported) format='Unsupported CPU architecture: %s' ;;
      arch_mismatch) format='The package architecture is %s, but this system is %s.' ;;
      glibc_too_old) format='This system has glibc %s; the package requires glibc %s or newer.' ;;
      binary_failed) format='The new redis-server cannot run on this system: %s' ;;
      version_unreadable) format='Unable to read the version from the new redis-server binary.' ;;
      version_mismatch) format='PACKAGE-INFO declares Redis %s, but the binary reports %s.' ;;
      systemd_unavailable) format='systemd is not running. Install on a systemd host or use --no-service for a binary-only installation.' ;;
      unit_replace) format='Replacing the existing service unit because --force-service was supplied: %s' ;;
      unit_conflict) format='%s is managed by another installation. Re-run with --force-service only if it may be replaced.' ;;
      group_created) format='Created system group %s.' ;;
      user_created) format='Created system user %s.' ;;
      service_failed) format='%s did not remain active. Check: journalctl -u %s' ;;
      state_invalid) format='Invalid installation state file: %s' ;;
      unmanaged_install) format='An unmanaged Redis installation was found. Re-run with --adopt only after confirming that it may be migrated.' ;;
      unexpected_path) format='Refusing to operate on an unexpected path: %s' ;;
      unknown_option) format='Unknown option: %s' ;;
      *) format="$key" ;;
    esac
  fi

  printf "$format" "$@"
}

info() {
  printf '[redis-package] %s\n' "$*"
}

warn() {
  printf '[redis-package] WARNING: %s\n' "$*" >&2
}

die() {
  printf '[redis-package] ERROR: %s\n' "$*" >&2
  exit 1
}

info_message() {
  info "$(message "$@")"
}

warn_message() {
  warn "$(message "$@")"
}

die_message() {
  die "$(message "$@")"
}

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die_message root_required
  fi
}

require_commands() {
  local command_name
  for command_name in "$@"; do
    command -v "$command_name" >/dev/null 2>&1 \
      || die_message command_missing "$command_name"
  done
}

metadata_value() {
  local file="$1"
  local key="$2"
  awk -F= -v wanted="$key" '$1 == wanted { sub(/^[^=]*=/, ""); print; exit }' "$file"
}

package_info_value() {
  local package_root="$1"
  local key="$2"
  metadata_value "$package_root/PACKAGE-INFO" "$key"
}

state_value() {
  local key="$1"
  [[ -f "$REDIS_STATE_FILE" ]] || return 0
  metadata_value "$REDIS_STATE_FILE" "$key"
}

managed_install_exists() {
  [[ -f "$REDIS_STATE_FILE" ]] \
    && [[ "$(state_value PACKAGE_ID)" == "$REDIS_PACKAGE_ID" ]]
}

validate_state_file() {
  [[ -f "$REDIS_STATE_FILE" ]] || return 0
  managed_install_exists || die_message state_invalid "$REDIS_STATE_FILE"
  [[ "$(state_value STATE_FORMAT)" == "1" ]] \
    || die_message state_invalid "$REDIS_STATE_FILE"
  [[ "$(state_value INSTALL_PREFIX)" == "$REDIS_INSTALL_PREFIX" ]] \
    || die_message state_invalid "$REDIS_STATE_FILE"
}

validate_package_root() {
  local package_root="$1"
  local package_info="$package_root/PACKAGE-INFO"

  [[ -x "$package_root/bin/redis-server" ]] \
    || die_message package_server_missing "$package_root"
  [[ -x "$package_root/bin/redis-cli" ]] \
    || die_message package_cli_missing "$package_root"
  [[ -f "$package_root/conf/redis.conf" ]] \
    || die_message package_config_missing "$package_root"
  [[ -f "$package_root/systemd/redis.service" ]] \
    || die_message package_unit_missing "$package_root"
  [[ -f "$package_info" ]] \
    || die_message package_info_missing "$package_root"
  [[ "$(package_info_value "$package_root" PACKAGE_ID)" == "$REDIS_PACKAGE_ID" ]] \
    || die_message package_info_invalid "$package_info"
  [[ "$(package_info_value "$package_root" PACKAGE_FORMAT)" == "1" ]] \
    || die_message package_info_invalid "$package_info"
  [[ "$(package_info_value "$package_root" OS)" == "linux" ]] \
    || die_message package_info_invalid "$package_info"
  [[ "$(package_info_value "$package_root" INSTALL_PREFIX)" == "$REDIS_INSTALL_PREFIX" ]] \
    || die_message package_prefix_invalid "$REDIS_INSTALL_PREFIX"
}

native_package_arch() {
  case "$(uname -m)" in
    x86_64|amd64) printf 'x64\n' ;;
    aarch64|arm64) printf 'arm64\n' ;;
    *) return 1 ;;
  esac
}

version_is_at_least() {
  local actual="$1"
  local required="$2"
  local actual_major actual_minor required_major required_minor

  IFS=. read -r actual_major actual_minor _ <<<"$actual"
  IFS=. read -r required_major required_minor _ <<<"$required"
  [[ "$actual_major" =~ ^[0-9]+$ && "$actual_minor" =~ ^[0-9]+$ ]] || return 1
  [[ "$required_major" =~ ^[0-9]+$ && "$required_minor" =~ ^[0-9]+$ ]] || return 1
  ((actual_major > required_major)) \
    || ((actual_major == required_major && actual_minor >= required_minor))
}

runtime_glibc_version() {
  local version_output
  command -v getconf >/dev/null 2>&1 || return 0
  version_output="$(LC_ALL=C getconf GNU_LIBC_VERSION 2>/dev/null || true)"
  sed -nE 's/^glibc[[:space:]]+([0-9]+\.[0-9]+).*$/\1/p' <<<"$version_output"
}

redis_version_from_binary() {
  local binary="$1"
  LC_ALL=C "$binary" --version \
    | sed -nE 's/^Redis server v=([^ ]+).*/\1/p' \
    | head -n 1
}

preflight_package_compatibility() {
  local package_root="$1"
  local system_name native_arch package_arch required_glibc actual_glibc
  local binary_output binary_version declared_version

  system_name="$(uname -s)"
  [[ "$system_name" == "Linux" ]] || die_message linux_required "$system_name"

  native_arch="$(native_package_arch || true)"
  [[ -n "$native_arch" ]] || die_message arch_unsupported "$(uname -m)"
  package_arch="$(package_info_value "$package_root" PACKAGE_ARCH)"
  [[ "$package_arch" == "$native_arch" ]] \
    || die_message arch_mismatch "$package_arch" "$native_arch"

  if [[ "$(package_info_value "$package_root" LIBC)" == "glibc" ]]; then
    required_glibc="$(package_info_value "$package_root" MIN_GLIBC)"
    actual_glibc="$(runtime_glibc_version)"
    if [[ -n "$actual_glibc" && -n "$required_glibc" ]] \
      && ! version_is_at_least "$actual_glibc" "$required_glibc"; then
      die_message glibc_too_old "$actual_glibc" "$required_glibc"
    fi
  fi

  if ! binary_output="$(LC_ALL=C "$package_root/bin/redis-server" --version 2>&1)"; then
    die_message binary_failed "$binary_output"
  fi
  binary_version="$(sed -nE 's/^Redis server v=([^ ]+).*/\1/p' <<<"$binary_output" | head -n 1)"
  [[ -n "$binary_version" ]] || die_message version_unreadable
  declared_version="$(package_info_value "$package_root" REDIS_VERSION)"
  [[ "$binary_version" == "$declared_version" ]] \
    || die_message version_mismatch "$declared_version" "$binary_version"
}

require_systemd_runtime() {
  require_commands systemctl
  [[ -d /run/systemd/system ]] || die_message systemd_unavailable
  systemctl show --property=Version --value >/dev/null 2>&1 \
    || die_message systemd_unavailable
}

service_fragment_path() {
  systemctl show --property=FragmentPath --value "$REDIS_SERVICE_NAME" 2>/dev/null || true
}

unit_file_is_managed() {
  local unit_file="$1"
  [[ -f "$unit_file" ]] \
    && grep -Fqx "$REDIS_UNIT_MARKER" "$unit_file" \
    && grep -Eq '^ExecStart=/usr/local/redis/bin/redis-server([[:space:]]|$)' "$unit_file"
}

assert_service_slot_available() {
  local force_service="$1"
  local fragment_path

  if [[ -f "$REDIS_SERVICE_UNIT" ]] \
    && ! unit_file_is_managed "$REDIS_SERVICE_UNIT"; then
    if [[ "$force_service" == true ]]; then
      warn_message unit_replace "$REDIS_SERVICE_UNIT"
    else
      die_message unit_conflict "$REDIS_SERVICE_UNIT"
    fi
  fi

  fragment_path="$(service_fragment_path)"
  if [[ -z "$fragment_path" || ! -f "$fragment_path" ]]; then
    return
  fi
  if unit_file_is_managed "$fragment_path"; then
    return
  fi
  if [[ "$force_service" == true ]]; then
    warn_message unit_replace "$fragment_path"
    return
  fi
  die_message unit_conflict "$fragment_path"
}

ACCOUNT_CREATED_USER=false
ACCOUNT_CREATED_GROUP=false

load_account_ownership_from_state() {
  local recorded_uid recorded_gid current_uid current_gid

  if managed_install_exists; then
    if [[ "$(state_value CREATED_USER)" == "1" ]]; then
      recorded_uid="$(state_value REDIS_UID)"
      if id "$REDIS_USER" >/dev/null 2>&1; then
        current_uid="$(id -u "$REDIS_USER")"
        if [[ -n "$recorded_uid" && "$current_uid" == "$recorded_uid" ]]; then
          ACCOUNT_CREATED_USER=true
        else
          warn "The redis user UID changed; package ownership was cleared. / redis 用户 UID 已变化，不再视为本项目创建。"
        fi
      else
        ACCOUNT_CREATED_USER=true
      fi
    fi

    if [[ "$(state_value CREATED_GROUP)" == "1" ]]; then
      recorded_gid="$(state_value REDIS_GID)"
      if getent group "$REDIS_GROUP" >/dev/null 2>&1; then
        current_gid="$(getent group "$REDIS_GROUP" | awk -F: '{print $3}')"
        if [[ -n "$recorded_gid" && "$current_gid" == "$recorded_gid" ]]; then
          ACCOUNT_CREATED_GROUP=true
        else
          warn "The redis group GID changed; package ownership was cleared. / redis 用户组 GID 已变化，不再视为本项目创建。"
        fi
      else
        ACCOUNT_CREATED_GROUP=true
      fi
    fi
  fi
  return 0
}

ensure_redis_account() {
  local nologin_shell

  if ! getent group "$REDIS_GROUP" >/dev/null 2>&1; then
    groupadd --system "$REDIS_GROUP"
    ACCOUNT_CREATED_GROUP=true
    info_message group_created "$REDIS_GROUP"
  fi

  if ! id "$REDIS_USER" >/dev/null 2>&1; then
    nologin_shell="$(command -v nologin || true)"
    [[ -n "$nologin_shell" ]] || nologin_shell="/sbin/nologin"
    useradd \
      --system \
      --gid "$REDIS_GROUP" \
      --home-dir "$REDIS_INSTALL_PREFIX/data" \
      --no-create-home \
      --shell "$nologin_shell" \
      "$REDIS_USER"
    ACCOUNT_CREATED_USER=true
    info_message user_created "$REDIS_USER"
  fi
}

prepare_runtime_layout() {
  install -d -m 0755 "$REDIS_INSTALL_PREFIX"
  install -d -o "$REDIS_USER" -g "$REDIS_GROUP" -m 0750 \
    "$REDIS_INSTALL_PREFIX/data"
  chown "$REDIS_USER:$REDIS_GROUP" "$REDIS_INSTALL_PREFIX/data"

  install -d -o root -g "$REDIS_GROUP" -m 0750 \
    "$REDIS_INSTALL_PREFIX/conf"
  for config_file in redis.conf sentinel.conf; do
    if [[ -f "$REDIS_INSTALL_PREFIX/conf/$config_file" ]]; then
      chown root:"$REDIS_GROUP" "$REDIS_INSTALL_PREFIX/conf/$config_file"
      chmod 0640 "$REDIS_INSTALL_PREFIX/conf/$config_file"
    fi
  done
}

install_default_configs() {
  local package_root="$1"
  local config_file

  install -d -o root -g "$REDIS_GROUP" -m 0750 "$REDIS_INSTALL_PREFIX/conf"
  for config_file in redis.conf sentinel.conf; do
    if [[ ! -e "$REDIS_INSTALL_PREFIX/conf/$config_file" ]]; then
      install -o root -g "$REDIS_GROUP" -m 0640 \
        "$package_root/conf/$config_file" \
        "$REDIS_INSTALL_PREFIX/conf/$config_file"
      if [[ "$config_file" == "redis.conf" ]]; then
        if grep -Eq '^dir[[:space:]]+' "$REDIS_INSTALL_PREFIX/conf/redis.conf"; then
          sed -i -E 's|^dir[[:space:]]+.*$|dir /usr/local/redis/data|' \
            "$REDIS_INSTALL_PREFIX/conf/redis.conf"
        else
          printf '\ndir /usr/local/redis/data\n' \
            >>"$REDIS_INSTALL_PREFIX/conf/redis.conf"
        fi
      fi
    fi
  done
}

install_service_unit() {
  local package_root="$1"
  install -D -o root -g root -m 0644 \
    "$package_root/systemd/redis.service" \
    "$REDIS_SERVICE_UNIT"
  systemctl daemon-reload
}

wait_for_service() {
  local attempt
  for attempt in {1..15}; do
    if systemctl is-active --quiet "$REDIS_SERVICE_NAME"; then
      return 0
    fi
    sleep 1
  done
  die_message service_failed "$REDIS_SERVICE_NAME" "$REDIS_SERVICE_NAME"
}

write_install_state() {
  local package_root="$1"
  local service_manager="$2"
  local temporary_state installed_at created_user created_group uid_value gid_value

  installed_at="$(state_value INSTALLED_AT)"
  [[ -n "$installed_at" ]] || installed_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  created_user=0
  created_group=0
  [[ "$ACCOUNT_CREATED_USER" == true ]] && created_user=1
  [[ "$ACCOUNT_CREATED_GROUP" == true ]] && created_group=1
  uid_value="$(id -u "$REDIS_USER")"
  gid_value="$(getent group "$REDIS_GROUP" | awk -F: '{print $3}')"
  temporary_state="$REDIS_INSTALL_PREFIX/.redis-package-state.tmp.$$"

  (
    umask 077
    {
      printf 'STATE_FORMAT=1\n'
      printf 'PACKAGE_ID=%s\n' "$REDIS_PACKAGE_ID"
      printf 'INSTALL_PREFIX=%s\n' "$REDIS_INSTALL_PREFIX"
      printf 'REDIS_VERSION=%s\n' "$(package_info_value "$package_root" REDIS_VERSION)"
      printf 'PACKAGE_VARIANT=%s\n' "$(package_info_value "$package_root" PACKAGE_VARIANT)"
      printf 'PACKAGE_ARCH=%s\n' "$(package_info_value "$package_root" PACKAGE_ARCH)"
      printf 'SERVICE_MANAGER=%s\n' "$service_manager"
      printf 'CREATED_USER=%s\n' "$created_user"
      printf 'CREATED_GROUP=%s\n' "$created_group"
      printf 'REDIS_UID=%s\n' "$uid_value"
      printf 'REDIS_GID=%s\n' "$gid_value"
      printf 'INSTALLED_AT=%s\n' "$installed_at"
      printf 'UPDATED_AT=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    } >"$temporary_state"
  )
  chown root:root "$temporary_state"
  chmod 0600 "$temporary_state"
  mv "$temporary_state" "$REDIS_STATE_FILE"
}
